/**
 * Life Admin — runtime config (generated by scripts/build-config.mjs)
 * Local: copy .env.example to .env and run npm run build:config
 * Vercel: set SUPABASE_URL and SUPABASE_ANON_KEY in project Environment Variables
 */
window.SUPABASE_URL = "PASTE_YOUR_SUPABASE_URL";
window.SUPABASE_ANON_KEY = "PASTE_YOUR_ANON_KEY";

window.DEV_USER_ROLE = "user";
window.DEV_USER_PLAN = "ai_chief_of_staff";
window.DEV_PREFER_CONFIG = false;
window.DEV_USER_EMAIL = "dev@lifeadmin.local";
window.DEV_USER_FULL_NAME = "Dev User";
