#!/usr/bin/env node
/**
 * Generates frontend/config.js from environment variables (Vercel / local .env).
 */
import { readFileSync, writeFileSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const envPath = join(root, ".env");
const outPath = join(root, "frontend", "config.js");

function loadEnvFile(path) {
  if (!existsSync(path)) return {};
  const text = readFileSync(path, "utf8");
  const out = {};
  for (const line of text.split("\n")) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const i = t.indexOf("=");
    if (i < 0) continue;
    const key = t.slice(0, i).trim();
    let val = t.slice(i + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

function env(key, fileEnv, fallback = "") {
  return process.env[key] || fileEnv[key] || fallback;
}

const fileEnv = loadEnvFile(envPath);

const url = env("SUPABASE_URL", fileEnv, "PASTE_YOUR_SUPABASE_URL");
const anonKey = env("SUPABASE_ANON_KEY", fileEnv, "PASTE_YOUR_ANON_KEY");
const devRole = env("DEV_USER_ROLE", fileEnv, "user");
const devPlan = env("DEV_USER_PLAN", fileEnv, "ai_chief_of_staff");
const devEmail = env("DEV_USER_EMAIL", fileEnv, "dev@lifeadmin.local");
const devName = env("DEV_USER_FULL_NAME", fileEnv, "Dev User");
const devPrefer = env("DEV_PREFER_CONFIG", fileEnv, "false");

const content = `/**
 * Life Admin — runtime config (generated by scripts/build-config.mjs)
 * Local: copy .env.example to .env and run npm run build:config
 * Vercel: set SUPABASE_URL and SUPABASE_ANON_KEY in project Environment Variables
 */
window.SUPABASE_URL = ${JSON.stringify(url)};
window.SUPABASE_ANON_KEY = ${JSON.stringify(anonKey)};

window.DEV_USER_ROLE = ${JSON.stringify(devRole)};
window.DEV_USER_PLAN = ${JSON.stringify(devPlan)};
window.DEV_PREFER_CONFIG = ${JSON.stringify(devPrefer === "true")};
window.DEV_USER_EMAIL = ${JSON.stringify(devEmail)};
window.DEV_USER_FULL_NAME = ${JSON.stringify(devName)};
`;

writeFileSync(outPath, content, "utf8");
console.log("Wrote frontend/config.js");
